title: Ben Stone # your name (or website title) here
logo: "/images/benstone_blackhillsnatlforest_square.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current graduate student at the University of Oklahoma, pursuing a M.S. in Geospatial Technologies. 
  <br>
  Graduated from Northern Illinois University with a B.S. in Environmental Studies, with an emphasis in Biodiversity and Environmental Restoration. 
  <br>
  I also achieved HAZWOPER, Wildlands Firefighter II, and Community Leadership and Civic Engagement certifications while at Northern Illinois University.
  <br>
  In my free time, I enjoy gardening, tending to my houseplants, studying local history, and researching genealogy. 
  <a href="https://www.linkedin.com/in/benjaminastone/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
