title: Ben Stone # your name (or website title) here
logo: "/images/benstone_blackhillsnatlforest.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Ben Stone. I've worked in the geographic information systems and engineering industries for a number of years, and have worked extensively with electric and potable, storm, and sewer water public utilities.  
  <br><br>
  I have experience with ArcMap, ArcGIS Pro, Python, Jupyter Notebook, R Studio, AutoCAD, pgAdmin/PostgreSQL, and the Adobe and Microsoft software suites. 
  <br><br>
  I graduated with my bachelors of science in Environmental Studies from Northern Illinois University, where I emphasized in Biodiversity and Environmental Restoration. I also achieved HAZWOPER, Wildlands Firefighter II, and Community Leadership and Civic Engagement certifications.
  I am currently enrolled at University of Oklahoma - Norman, pursuing a master's degree in Geospatial Technologies, and am anticipating a graduation date of May 2023. 
  <br><br>
  <a href="https://www.linkedin.com/in/benjaminastone/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
